# Generated by Django 5.0.4 on 2024-04-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor_type', models.CharField(max_length=100)),
                ('ram_size', models.IntegerField()),
                ('storage_size', models.IntegerField()),
                ('storage_type', models.CharField(max_length=50)),
                ('display_size', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
