# Generated by Django 5.0.1 on 2024-04-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_laptop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='release_date',
        ),
    ]
